version: '3'
services:
  postgres:
    image: 'postgres:14.5'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/users.sql:/docker-entrypoint-initdb.d/create_tables.sql
  go-webapp:
    build: .
    restart: always
    environment:
      DSN: "host=postgres port=5432 user=postgres password=postgres dbname=users sslmode=disable timezone=UTC connect_timeout=5"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '8080:8080'
    depends_on:
      - postgres